# -*- coding: utf-8 -*-
"""7_Correlation_and_Beta.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import pandas as pd
import yfinance as yf
from all_seeing_eye_iteration_1 import tickers

st.title("📊 Correlation & Beta vs Sharia Index")

index_symbol = "^J141.JO"

if st.button("Compute Metrics"):
    # download ALL tickers
    data = {}
    for t in tickers + [index_symbol]:
        df = yf.Ticker(t).history(period="5y")["Close"]
        if not df.empty:
            data[t] = df

    df = pd.DataFrame(data).dropna()
    index = df[index_symbol]

    corrs = {}
    betas = {}

    for t in tickers:
        corrs[t] = df[t].corr(index)

        # compute beta
        lr = pd.DataFrame({
            "stock": df[t].pct_change(),
            "market": index.pct_change()
        }).dropna()
        beta = lr["stock"].cov(lr["market"]) / lr["market"].var()
        betas[t] = beta

    st.write("### Correlation with Index")
    st.dataframe(pd.DataFrame.from_dict(corrs, orient="index"))

    st.write("### Beta vs Index")
    st.dataframe(pd.DataFrame.from_dict(betas, orient="index"))