# -*- coding: utf-8 -*-
"""5_Probabilistic_LSTM_Ensemble.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import yfinance as yf
from all_seeing_eye_iteration_1 import ProbabilisticEnsemblePredictor

st.title("🎲 Probabilistic LSTM Ensemble (Monte-Carlo Dropout)")

ticker = st.text_input("Ticker:", "IMP.JO")

if st.button("Run Probabilistic Model"):
    hist = yf.Ticker(ticker).history(period="10y")

    predictor = ProbabilisticEnsemblePredictor()
    predictor.train(hist)

    results = predictor.predict_future(hist)

    st.line_chart(results["mean"])
    st.area_chart(pd.DataFrame({
        "P5": results["p5"],
        "P95": results["p95"]
    }))