# -*- coding: utf-8 -*-
"""6_Backtesting_ARIMA_ML_MonteCarlo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
from all_seeing_eye_iteration_1 import main as backtest_main

st.title("📉 Backtesting: ARIMA, ML & Monte Carlo")

st.write("This runs the complete backtesting engine from your notebook.")

if st.button("Start Backtesting"):
    backtest_main()
    st.success("Backtesting complete.")