# -*- coding: utf-8 -*-
"""1_RSI_and_Basic_Indicators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import yfinance as yf
import pandas as pd
from all_seeing_eye_iteration_1 import calculate_rsi

st.title("📊 RSI & Basic Technical Indicators")

ticker = st.text_input("Enter Ticker:", "IMP.JO")

if st.button("Run"):
    data = yf.download(ticker, period="1y")
    if data.empty:
        st.error("No data found.")
    else:
        rsi_value = calculate_rsi(data["Close"])
        st.metric("RSI (14-day)", round(rsi_value, 2))
        st.line_chart(data["Close"])