# -*- coding: utf-8 -*-
"""2_Holt_Winters_Forecast.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import yfinance as yf
import pandas as pd
from statsmodels.tsa.holtwinters import ExponentialSmoothing
from datetime import timedelta

st.title("📈 Holt-Winters Forecast (3-Month)")

ticker = st.text_input("Enter Stock Ticker:", "IMP.JO")
forecast_days = 63

if st.button("Run Forecast"):
    data = yf.download(ticker, period="5y")[["Close"]].dropna()

    model = ExponentialSmoothing(data["Close"], trend="add", seasonal=None)
    model_fit = model.fit()
    forecast = model_fit.forecast(forecast_days)

    st.line_chart(pd.concat([data["Close"], forecast]))