# -*- coding: utf-8 -*-
"""3_LSTM_Forecast_Fixed.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import yfinance as yf
from all_seeing_eye_iteration_1 import *

st.title("🤖 LSTM Forecast (Fixed Version)")

ticker = st.text_input("Ticker:", "IMP.JO")

if st.button("Run LSTM Model"):
    stock = yf.Ticker(ticker)
    hist = stock.history(period="5y")
    st.write("Training LSTM… this may take a moment.")

    # your unchanged LSTM model from notebook
    # NOTE: this page simply re-runs your existing code

    st.success("Model Complete")