# -*- coding: utf-8 -*-
"""4_Enhanced_LSTM_Ensemble.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

import streamlit as st
import yfinance as yf
from all_seeing_eye_iteration_1 import EnhancedStockPredictor

st.title("🧠 Enhanced LSTM Ensemble")

ticker = st.text_input("Enter Ticker:", "IMP.JO")

if st.button("Run Enhanced Model"):
    hist = yf.Ticker(ticker).history(period="5y")

    predictor = EnhancedStockPredictor()
    metrics = predictor.train(hist)

    if metrics:
        st.write(metrics)
        st.success("Training Complete")

        forecast = predictor.predict_future(hist)
        st.line_chart(forecast)