# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cLvODfHrIMAovsosiX2olAhIk0iiFGJI
"""

# config.py

import pandas as pd
from datetime import datetime

# --- Global App Configuration ---
DEFAULT_STOCKS = ['IMP.JO', 'APN.JO', 'BHG.JO', 'AGL.JO', 'SOL.JO', 'GFI.JO', 'ANG.JO', 'VAL.JO', 'NPH.JO', 'CLS.JO', 'MRP.JO', 'MTN.JO', 'VOD.JO', 'OMN.JO', 'SDO.JO', 'RFG.JO', 'PPC.JO', 'TBS.JO']
START_DATE = '2020-01-01'
END_DATE = datetime.today().strftime('%Y-%m-%d')

# --- Clustering Model Settings ---
N_CLUSTERS = 5 # Default for the app (can be changed by user)
TRADING_DAYS_PER_YEAR = 252
FUNDAMENTAL_FEATURES = ['priceToBook', 'trailingPE', 'debtToEquity', 'dividendYield']

# --- Time Series Model Settings ---
FORECAST_DAYS_TS = 63  # ~3 months trading days
TS_TICKERS = ["IMP.JO", "ANG.JO", "GFI.JO","VAL.JO","APN.JO","NPH.JO","CLS.JO","MRP.JO","BHG.JO","OMN.JO","PPC.JO","TBS.JO"]

# --- Index Comparison Settings ---
SHARIA_INDEX = "^J141.JO"